CREATE EXTENSION pgxcrypto_pwhash;

--
-- Try settings for pgxcrypto.argon2_default_backend
--

-- should fail
SET pgxcrypto.argon2_default_backend = 'blabla';

-- should succeed
SET pgxcrypto.argon2_default_backend = 'openssl';
SHOW pgxcrypto.argon2_default_backend;

SET pgxcrypto.argon2_default_backend = 'libargon2';
SHOW pgxcrypto.argon2_default_backend;

-- back to default
RESET pgxcrypto.argon2_default_backend;
SHOW pgxcrypto.argon2_default_backend;

--
-- Tests for argon2id
--

--
-- Reference source comparison to python passlib
--

--
-- Compare hash values formerly derived by python passlib with default settings
--
-- Hash created by pythons' passlib:

-- from passlib.hash import argon2
-- h = (argon2.hash("password"))
-- h = (argon2.using(type="I").using(rounds=32).hash("password"))
-- h = (argon2.using(rounds=12).using(memory_cost=524144).hash("password"))

-- Needs to be off, since python's passlib doesn't pad at all
SET pgxcrypto.always_pad_base64 TO off;

--------------------------------------
-- Tests with default OpenSSL backend
--------------------------------------

-- With Argon2id

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=3,p=4$u9ca4zxn7H0PISSE0HqP8Q$yeN3V5sfotE6xjbD+1oBNXyF6ZkgDAlsrnJvYbOgbY4') = '$argon2id$v=19$m=65536,t=3,p=4$u9ca4zxn7H0PISSE0HqP8Q$yeN3V5sfotE6xjbD+1oBNXyF6ZkgDAlsrnJvYbOgbY4';

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=32,p=4$nHNOyRkjBMDYW8sZo7S29g$iNUvxeJFuWD8J80LlQ1G1uJ9rRIYSBMM11vQP6YJLec') = '$argon2id$v=19$m=65536,t=32,p=4$nHNOyRkjBMDYW8sZo7S29g$iNUvxeJFuWD8J80LlQ1G1uJ9rRIYSBMM11vQP6YJLec';

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=524144,t=12,p=4$x3gPgZBybs05x/g/R4ix1g$PdtQc0Ew4cmDTjlgONywuuRymhVqricqoV+t0L3+7fI') = '$argon2id$v=19$m=524144,t=12,p=4$x3gPgZBybs05x/g/R4ix1g$PdtQc0Ew4cmDTjlgONywuuRymhVqricqoV+t0L3+7fI';

-- Same with Argon2i
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$3JsTYkxJyXmPsbbW+h+DEA$PfNhqviX6Vdir2yjZGvdNsZBtyGGK6OspQ8dBHKtxjw') = '$argon2i$v=19$m=65536,t=3,p=4$3JsTYkxJyXmPsbbW+h+DEA$PfNhqviX6Vdir2yjZGvdNsZBtyGGK6OspQ8dBHKtxjw';

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=32,p=4$KwVgjNE6B8A4x1gLQUgJ4Q$lIKr0C06qclmZ2hMt0hfEYa2zVIxoUrRyL4WqZEM9Ik') = '$argon2i$v=19$m=65536,t=32,p=4$KwVgjNE6B8A4x1gLQUgJ4Q$lIKr0C06qclmZ2hMt0hfEYa2zVIxoUrRyL4WqZEM9Ik';

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=32,p=4$g/C+9/6/N+Zca+39v/e+Vw$hwV/1QN+JWWaAyuj2iG79m/fnsfK8V64VObms58aNKY') = '$argon2i$v=19$m=65536,t=32,p=4$g/C+9/6/N+Zca+39v/e+Vw$hwV/1QN+JWWaAyuj2iG79m/fnsfK8V64VObms58aNKY';

-- And Argon2d
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$QChlbI0xRgjBOOe8t3au1Q$8Qb01rXObi+4PsLGKLabqlSN/kWpBPR/otSZYSIX04c') = '$argon2i$v=19$m=65536,t=3,p=4$QChlbI0xRgjBOOe8t3au1Q$8Qb01rXObi+4PsLGKLabqlSN/kWpBPR/otSZYSIX04c';

--
-- Compare hashes generated by Argon2 reference implementation
--
-- The hashes which are compared are generated by the argon2 CLI tool like this:
--
-- echo -n password | argon2 12345678 -id -k 65536 -p 4 -e
--

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$2sE3QrtIr+1LWoXKNOp78utMyP0aUrKzzJaDjgNWaac') = '$argon2id$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$2sE3QrtIr+1LWoXKNOp78utMyP0aUrKzzJaDjgNWaac';

-- echo -n password | argon2 12345678 -id -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$5yr8dXSYcZjcMH5jBzwNm0D84iQOKLGLOWsQeKUUHpE') = '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$5yr8dXSYcZjcMH5jBzwNm0D84iQOKLGLOWsQeKUUHpE';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -id -k 4096 -p 1 -e

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5MA$pptxGYuibkAGG9bVRNAxgEv6/OMVVEahqS8vEmo/B2g') = '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5MA$pptxGYuibkAGG9bVRNAxgEv6/OMVVEahqS8vEmo/B2g';

--
-- same with Argon2i
--
-- echo -n password | argon2 12345678 -i -k 65536 -p 4 -e
--

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$BvKUwNCmr7GPzmR+EyZJdBTOWvRPvaz2lNpZgWdAN3A') = '$argon2i$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$BvKUwNCmr7GPzmR+EyZJdBTOWvRPvaz2lNpZgWdAN3A';

-- echo -n password | argon2 12345678 -i -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$y8JaUwdNBwIXjh8MsBXCpGZ/avW2uhupKJsomvqnyiY') = '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$y8JaUwdNBwIXjh8MsBXCpGZ/avW2uhupKJsomvqnyiY';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -i -k 4096 -p 1 -e

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$oB0yBJVFa/Q9LPtmGL6SpjeaKg++Cloipto5OiYzCRU') = '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$oB0yBJVFa/Q9LPtmGL6SpjeaKg++Cloipto5OiYzCRU';

--
-- Same with Argon2d
--
-- echo -n password | argon2 12345678 -d -k 65536 -p 4 -e

SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$h+HoUsia1leIw6QQtzEFgergF3Ccud96oLEaS0ZOnMU') = '$argon2d$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$h+HoUsia1leIw6QQtzEFgergF3Ccud96oLEaS0ZOnMU';

-- echo -n password | argon2 12345678 -d -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$YDBvrlalKVUif4UV+7RYk2s6F1ucueZZ/BibQz4zsa8') = '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$YDBvrlalKVUif4UV+7RYk2s6F1ucueZZ/BibQz4zsa8';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -d -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$TW92egXZew84K8pX5fIX9IGN0i6FplcIioHC7J1aqSc') = '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$TW92egXZew84K8pX5fIX9IGN0i6FplcIioHC7J1aqSc';

--------------------------------------
-- Tests with libargon2
--------------------------------------

-- With Argon2id
SET pgxcrypto.argon2_default_backend TO 'libargon2';

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=3,p=4$u9ca4zxn7H0PISSE0HqP8Q$yeN3V5sfotE6xjbD+1oBNXyF6ZkgDAlsrnJvYbOgbY4') = '$argon2id$v=19$m=65536,t=3,p=4$u9ca4zxn7H0PISSE0HqP8Q$yeN3V5sfotE6xjbD+1oBNXyF6ZkgDAlsrnJvYbOgbY4';

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=32,p=4$nHNOyRkjBMDYW8sZo7S29g$iNUvxeJFuWD8J80LlQ1G1uJ9rRIYSBMM11vQP6YJLec') = '$argon2id$v=19$m=65536,t=32,p=4$nHNOyRkjBMDYW8sZo7S29g$iNUvxeJFuWD8J80LlQ1G1uJ9rRIYSBMM11vQP6YJLec';

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=524144,t=12,p=4$x3gPgZBybs05x/g/R4ix1g$PdtQc0Ew4cmDTjlgONywuuRymhVqricqoV+t0L3+7fI') = '$argon2id$v=19$m=524144,t=12,p=4$x3gPgZBybs05x/g/R4ix1g$PdtQc0Ew4cmDTjlgONywuuRymhVqricqoV+t0L3+7fI';

-- Same with Argon2i
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$3JsTYkxJyXmPsbbW+h+DEA$PfNhqviX6Vdir2yjZGvdNsZBtyGGK6OspQ8dBHKtxjw') = '$argon2i$v=19$m=65536,t=3,p=4$3JsTYkxJyXmPsbbW+h+DEA$PfNhqviX6Vdir2yjZGvdNsZBtyGGK6OspQ8dBHKtxjw';

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=32,p=4$KwVgjNE6B8A4x1gLQUgJ4Q$lIKr0C06qclmZ2hMt0hfEYa2zVIxoUrRyL4WqZEM9Ik') = '$argon2i$v=19$m=65536,t=32,p=4$KwVgjNE6B8A4x1gLQUgJ4Q$lIKr0C06qclmZ2hMt0hfEYa2zVIxoUrRyL4WqZEM9Ik';

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=32,p=4$g/C+9/6/N+Zca+39v/e+Vw$hwV/1QN+JWWaAyuj2iG79m/fnsfK8V64VObms58aNKY') = '$argon2i$v=19$m=65536,t=32,p=4$g/C+9/6/N+Zca+39v/e+Vw$hwV/1QN+JWWaAyuj2iG79m/fnsfK8V64VObms58aNKY';

-- And Argon2d
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$QChlbI0xRgjBOOe8t3au1Q$8Qb01rXObi+4PsLGKLabqlSN/kWpBPR/otSZYSIX04c') = '$argon2i$v=19$m=65536,t=3,p=4$QChlbI0xRgjBOOe8t3au1Q$8Qb01rXObi+4PsLGKLabqlSN/kWpBPR/otSZYSIX04c';

--
-- Compare hashes generated by Argon2 reference implementation
--
-- The hashes which are compared are generated by the argon2 CLI tool like this:
--
-- echo -n password | argon2 12345678 -id -k 65536 -p 4 -e
--

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$2sE3QrtIr+1LWoXKNOp78utMyP0aUrKzzJaDjgNWaac') = '$argon2id$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$2sE3QrtIr+1LWoXKNOp78utMyP0aUrKzzJaDjgNWaac';

-- echo -n password | argon2 12345678 -id -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$5yr8dXSYcZjcMH5jBzwNm0D84iQOKLGLOWsQeKUUHpE') = '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$5yr8dXSYcZjcMH5jBzwNm0D84iQOKLGLOWsQeKUUHpE';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -id -k 4096 -p 1 -e

SELECT pgxcrypto_argon2('password', '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5MA$pptxGYuibkAGG9bVRNAxgEv6/OMVVEahqS8vEmo/B2g') = '$argon2id$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5MA$pptxGYuibkAGG9bVRNAxgEv6/OMVVEahqS8vEmo/B2g';

--
-- same with Argon2i
--
-- echo -n password | argon2 12345678 -i -k 65536 -p 4 -e
--

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$BvKUwNCmr7GPzmR+EyZJdBTOWvRPvaz2lNpZgWdAN3A') = '$argon2i$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$BvKUwNCmr7GPzmR+EyZJdBTOWvRPvaz2lNpZgWdAN3A';

-- echo -n password | argon2 12345678 -i -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$y8JaUwdNBwIXjh8MsBXCpGZ/avW2uhupKJsomvqnyiY') = '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$y8JaUwdNBwIXjh8MsBXCpGZ/avW2uhupKJsomvqnyiY';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -i -k 4096 -p 1 -e

SELECT pgxcrypto_argon2('password', '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$oB0yBJVFa/Q9LPtmGL6SpjeaKg++Cloipto5OiYzCRU') = '$argon2i$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$oB0yBJVFa/Q9LPtmGL6SpjeaKg++Cloipto5OiYzCRU';

--
-- Same with Argon2d
--
-- echo -n password | argon2 12345678 -d -k 65536 -p 4 -e

SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$h+HoUsia1leIw6QQtzEFgergF3Ccud96oLEaS0ZOnMU') = '$argon2d$v=19$m=65536,t=3,p=4$MTIzNDU2Nzg$h+HoUsia1leIw6QQtzEFgergF3Ccud96oLEaS0ZOnMU';

-- echo -n password | argon2 12345678 -d -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$YDBvrlalKVUif4UV+7RYk2s6F1ucueZZ/BibQz4zsa8') = '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg$YDBvrlalKVUif4UV+7RYk2s6F1ucueZZ/BibQz4zsa8';

-- salt length not divisible by 4 (will be padded by OpenSSL)
-- echo -n password | argon2 123456789 -d -k 4096 -p 1 -e
SELECT pgxcrypto_argon2('password', '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$TW92egXZew84K8pX5fIX9IGN0i6FplcIioHC7J1aqSc') = '$argon2d$v=19$m=4096,t=3,p=1$MTIzNDU2Nzg5$TW92egXZew84K8pX5fIX9IGN0i6FplcIioHC7J1aqSc';

RESET pgxcrpyto.argon2_default_backend;

----------------------------------------------------------
-- Test generating Argon2 hashes with pgxcrypto_gen_salt()
----------------------------------------------------------

CREATE TABLE pgxcrypto_test_argon2(pw text NOT NULL, salt text NOT NULL, hash text);
INSERT INTO pgxcrypto_test_argon2(pw, salt) VALUES('password', pgxcrypto_gen_salt('argon2id','memcost=4096', 'parallelism=1', 'rounds=3'));
UPDATE pgxcrypto_test_argon2 SET hash = pgxcrypto_argon2('password', salt) WHERE pw = 'password';

SELECT hash = pgxcrypto_argon2(pw, salt) FROM pgxcrypto_test_argon2;

DELETE FROM pgxcrypto_test_argon2;

-- choose libargon2 backend via salt settings
INSERT INTO pgxcrypto_test_argon2(pw, salt) VALUES('password', pgxcrypto_gen_salt('argon2id','memcost=4096', 'parallelism=1', 'rounds=3', 'backend=libargon2'));
UPDATE pgxcrypto_test_argon2 SET hash = pgxcrypto_argon2('password', salt) WHERE pw = 'password';

SELECT hash = pgxcrypto_argon2(pw, salt) FROM pgxcrypto_test_argon2;

DELETE FROM pgxcrypto_test_argon2;

-- switch hash backends in between
RESET pgxcrypto.argon2_default_backend;
SHOW pgxcrypto.argon2_default_backend;
INSERT INTO pgxcrypto_test_argon2(pw, salt) VALUES('password', pgxcrypto_gen_salt('argon2id','memcost=4096', 'parallelism=1', 'rounds=3'));
UPDATE pgxcrypto_test_argon2 SET hash = pgxcrypto_argon2('password', salt) WHERE pw = 'password';

SET pgxcrypto.argon2_default_backend TO 'libargon2';
SHOW pgxcrypto.argon2_default_backend;

SELECT hash = pgxcrypto_argon2(pw, salt) FROM pgxcrypto_test_argon2;
RESET pgxcrypto.argon2_default_backend;

DROP TABLE pgxcrypto_test_argon2;

--
-- Checks for scrypt
--
-- The hashes we compare here are derived via python's passlib again
--
-- h = scrypt.using(salt=bytes("12345678", "utf-8")).hash("password")
--
SELECT pgxcrypto_scrypt('password', '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg$NuB+vs2zc0fb2UzIRwwAV6ZWb3St8+X9IedYI1gQsoo') = '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg$NuB+vs2zc0fb2UzIRwwAV6ZWb3St8+X9IedYI1gQsoo';

--
-- Check if parameters get applied
--
-- h = scrypt.using(salt=bytes("12345678", "utf-8")).using=(rounds=8).using(block_size=16).hash("password")
--
SELECT pgxcrypto_scrypt('password', '$scrypt$ln=8,r=16,p=1$MTIzNDU2Nzg$tEmA9TbF8lFDbMySWVfYoEqW2ywo6Qr8vu/sHHwVyDs') = '$scrypt$ln=8,r=16,p=1$MTIzNDU2Nzg$tEmA9TbF8lFDbMySWVfYoEqW2ywo6Qr8vu/sHHwVyDs';

--
-- Check uneven base64 salt (needs padding) and is handled according to pgxcrypto.always_pad_base64
--
-- h = scrypt.using(salt=bytes("123456789", "utf-8")).hash("password")
--
SELECT pgxcrypto_scrypt('password', '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84') = '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84';

--
-- Check with crypt identifier
--
-- Should fail, since scrypt ident is expected
SELECT pgxcrypto_scrypt('password', '$7$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84') = '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84';

-- Same, but this time with correct identifier
SELECT pgxcrypto_scrypt('password', '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84') = '$scrypt$ln=16,r=8,p=1$MTIzNDU2Nzg5$owI4pAfxQFH5mayb2BJed7ltHms8Z+M1JEQ/PIvuW84';

-- Same test, but this time with pgxcrypto.always_pad_base64 set to on (salt and password hash
-- should be padded)
SET pgxcrypto.always_pad_base64 TO on;
SELECT pgxcrypto_scrypt('password', '$scrypt$ln=16,r=8,p=1$MTIzNDU=$UrgkUooL3HseyjbLegKgNKz2B/0mlHRg+ZJu6DuXK00=') = '$scrypt$ln=16,r=8,p=1$MTIzNDU=$UrgkUooL3HseyjbLegKgNKz2B/0mlHRg+ZJu6DuXK00=';

SET pgxcrypto.always_pad_base64 TO off;

-- should fail, options string not present
SELECT pgxcrypto_scrypt('password', '$scrypt$MTIzNDU=$UrgkUooL3HseyjbLegKgNKz2B/0mlHRg+ZJu6DuXK00');

-- should fail, obscure option specification
SELECT pgxcrypto_scrypt('password', '$scrypt$M$TIzNDU=$UrgkUooL3HseyjbLegKgNKz2B/0mlHRg+ZJu6DuXK00=');

--
-- Test crypt() implementation
--

-- Should succeed
SELECT pgxcrypto_scrypt_crypt('password', '$7$DU..../....OhzHZvHVazzr5gCG7jotQ0$aehDO6CrqD4ITgsiLqw3EmIYyulY/tZSF9ARYtZN4U/') = '$7$DU..../....OhzHZvHVazzr5gCG7jotQ0$aehDO6CrqD4ITgsiLqw3EmIYyulY/tZSF9ARYtZN4U/';

-- Should fail, obscure salt
SELECT pgxcrypto_scrypt_crypt('password', '$7$abcdefghijkl');

-- -------------------------------------------------------------------------------------------------
-- Checks for yescrypt hashing
--
-- Currently this is supported on platforms with advanced libxcrypt support only (Linux, BSD).
-- So checks might fail in case support wasn't available during compilation of the extension
-- -------------------------------------------------------------------------------------------------

--
-- Compare hashes derived via test/crypt_gensalt_yescrypt password '$y$jAT$ymqO.hmB133abiOGZqA4f/'
-- (parameter rounds=6)
--
SELECT pgxcrypto_yescrypt_crypt('password', '$y$jAT$ymqO.hmB133abiOGZqA4f/') = '$y$jAT$ymqO.hmB133abiOGZqA4f/$ff0GrluBLpVssGRjSIYMUG2E7JWH722mSyalZT3o3E3';

-- Following tests should fail
-- Note: We need lc_messages set to C, otherwise we get localized errors from libxcrypt
SET lc_messages TO 'C';
SELECT pgxcrypto_yescrypt_crypt('password', '$y$');
SELECT pgxcrypto_yescrypt_crypt('password', '$y$$');
SELECT pgxcrypto_yescrypt_crypt('password', '');
RESET lc_messages;

----------------------------------------------------------
-- Test generating yescrypt hashes with pgxcrypto_gen_salt()
----------------------------------------------------------

CREATE TABLE pgxcrypto_test_yescrypt(pw text NOT NULL, salt text NOT NULL, hash text);
INSERT INTO pgxcrypto_test_yescrypt(pw, salt) VALUES('password', pgxcrypto_gen_salt('yescrypt', 'rounds=3'));
UPDATE pgxcrypto_test_yescrypt SET hash = pgxcrypto_yescrypt_crypt('password', salt) WHERE pw = 'password';

SELECT hash = pgxcrypto_yescrypt_crypt(pw, salt) FROM pgxcrypto_test_yescrypt;

DROP TABLE pgxcrypto_test_yescrypt;
